module.exports = [
    {
        name: "Victoria Hayward",
        sport_id: 1,
        position: "Outfield",
        number: "8",
        image: "https://equipmeserver.herokuapp.com/images/athletes/victoria-hayward-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/victoria-hayward-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/victoria-hayward-offense.jpg",
        description: "Team Canada Outfielder, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "31c7dd34-459d-461c-a85a-27ab9433bfea",
        batId: "ffd26156-2346-451f-923a-64f28c3fd3c7",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 215,
        gloveOffsetY: 49,
        cleatOffsetX: 90,
        cleatOffsetY: 440,
        glove_id: 26,
        bat_id: 8,
        cleat_id: 1 
    },
    {
        name: "Natalie Wideman",
        sport_id: 1,
        number: "2",
        position: "Catcher/Utility",
        image: "https://equipmeserver.herokuapp.com/images/athletes/natalie-wideman-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/natalie-wideman-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/natalie-wideman-offense.jpg",
        description: "Team Canada Catcher/Utility Player, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "e4341bef-8bdb-4f78-bad7-108061481753",
        batId: "db7bfe71-2375-4223-9007-dc390243dfd4",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 264,
        gloveOffsetY: 353,
        cleatOffsetX: 50,
        cleatOffsetY: 418,
        glove_id: 25,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Erika Polidori",
        sport_id: 1,
        number: "3",
        position: "Outfield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/erika-polidori-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/erika-polidori-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/erika-polidori-offense.jpg",
        description: "Team Canada Outfielder, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "851e4e1e-3397-4053-9a15-68ddd9540f6d",
        batId: "ffd26156-2346-451f-923a-64f28c3fd3c7",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 160,
        gloveOffsetY: 105,
        cleatOffsetX: 113,
        cleatOffsetY: 460,
        glove_id: 12,
        bat_id: 8,
        cleat_id: 1 
    },
    {
        name: "Janet Leung",
        sport_id: 1,
        number: "14",
        position: "Infield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/janet-leung-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/janet-leung-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/janet-leung-offense.jpg",
        description: "Team Canada Shortstop, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "31c7dd34-459d-461c-a85a-27ab9433bfea",
        batId: "db7bfe71-2375-4223-9007-dc390243dfd4",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 235,
        gloveOffsetY: 156,
        cleatOffsetX: 178,
        cleatOffsetY: 430,
        glove_id: 30,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Sara Groenewegen",
        sport_id: 1,
        number: "17",
        position: "Pitcher",
        image: "https://equipmeserver.herokuapp.com/images/athletes/sara-groenewegen-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/sara-groenewegen-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/sara-groenewegen-offense.jpg",
        description: "Team Canada Pitcher, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "2b2723d7-ca68-491f-ae10-ea0604708838",
        batId: "ffd26156-2346-451f-923a-64f28c3fd3c7",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 260,
        gloveOffsetY: 30,
        cleatOffsetX: 28,
        cleatOffsetY: 274,
        glove_id: 12,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Emma Entzminger",
        sport_id: 1,
        number: "19",
        position: "Infield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/emma-entzminger-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/emma-entzminger-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/emma-entzminger-offense.jpg",
        description: "Team Canada 3rd Baseman, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "e4341bef-8bdb-4f78-bad7-108061481753",
        batId: "db7bfe71-2375-4223-9007-dc390243dfd4",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 73,
        gloveOffsetY: 157,
        cleatOffsetX: 168,
        cleatOffsetY: 335,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Larissa Franklin",
        sport_id: 1,
        number: "26",
        position: "Outfield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/larissa-franklin-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/larissa-franklin-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/larissa-franklin-offense.jpg",
        description: "Team Canada Outfielder, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "a518de29-56f3-4020-b4c9-9ee5c58faa4c",
        batId: "db7bfe71-2375-4223-9007-dc390243dfd4",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 185,
        gloveOffsetY: 265,
        cleatOffsetX: 122,
        cleatOffsetY: 407,
        glove_id: 36,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Jennifer Salling",
        sport_id: 1,
        number: "8",
        position: "Infield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/jenn-salling-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/jenn-salling-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/jenn-salling-offense.jpg",
        description: "Team Canada First baseman, 2x Olympian, Tokyo 2020 Olympic Bronze Medalist, and NCAA National Champion",
        gloveId: "29f8590d-613a-426b-b8cf-bee42346e758",
        batId: "db7bfe71-2375-4223-9007-dc390243dfd4",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 99,
        gloveOffsetY: 210,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Jenna Caira",
        sport_id: 1,
        number: "29",
        position: "Pitcher",
        image: "https://equipmeserver.herokuapp.com/images/athletes/jenna-caira-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/jenna-caira-defense.jpg",
        description: "Team Canada Pitcher, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "b24189ad-e804-4c42-b3b1-338eb73b82ec",
        cleatId: "l0a2kj5b-a49d-4432-80xa-d09as124g2b6",
        gloveOffsetX: 111,
        gloveOffsetY: 91,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Kelsey Harshman",
        sport_id: 1,
        number: "1",
        position: "Infield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/kelsey-harshman-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/kelsey-harshman-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/kelsey-harshman-offense.jpg",
        description: "Team Canada 2nd Baseman, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "9a24c527-61b4-4640-8af0-f64b11437fe4",
        gloveOffsetX: 215,
        gloveOffsetY: 150,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Kaleigh Rafter",
        sport_id: 1,
        number: "55",
        position: "Catcher",
        image: "https://equipmeserver.herokuapp.com/images/athletes/kaleigh-rafter-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/kaleigh-rafter-defense.jpg",
        description: "Team Canada Catcher, 2x Olympian, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "684912b1-e1b7-41fb-8d8b-11cb2342574d",
        gloveOffsetX: 270,
        gloveOffsetY: 253,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Joey Lye",
        sport_id: 1,
        number: "5",
        position: "Utility",
        image: "https://equipmeserver.herokuapp.com/images/athletes/joey-lye-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/joey-lye-defense.jpg",
        image2: "https://equipmeserver.herokuapp.com/images/athletes/joey-lye-offense.jpg",
        description: "Team Canada Utility (Infield/Outfield), Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "78eb88e6-e376-4c9f-998f-fe4c1145bee9",
        gloveOffsetX: 190,
        gloveOffsetY: 93,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Danielle Lawrie",
        sport_id: 1,
        number: "13",
        position: "Pitcher",
        image: "https://equipmeserver.herokuapp.com/images/athletes/danielle-lawrie-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/danielle-lawrie-defense.jpg",
        description: "Team Canada Pitcher, 2x Olympian, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "df0b1eed-296a-4095-adaf-5eace2aba514",
        gloveOffsetX: 250,
        gloveOffsetY: 58,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Lauren Bay",
        sport_id: 1,
        number: "38",
        position: "Pitcher",
        image: "https://equipmeserver.herokuapp.com/images/athletes/lauren-bay-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/lauren-bay-defense.jpg",
        description: "Team Canada Pitcher, 2x Olympian, Tokyo 2020 Olympic Bronze Medalist",
        gloveId:"df0b1eed-296a-4095-adaf-5eace2aba514",
        gloveOffsetX: 205,
        gloveOffsetY: 145,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    },
    {
        name: "Jennifer Gilbert",
        sport_id: 1,
        number: "25",
        position: "Outfield",
        image: "https://equipmeserver.herokuapp.com/images/athletes/jen-gilbert-headshot.jpg",
        image1: "https://equipmeserver.herokuapp.com/images/athletes/jen-gilbert-defense.jpg",
        description: "Team Canada Outfield, Tokyo 2020 Olympic Bronze Medalist",
        gloveId: "31c7dd34-459d-461c-a85a-27ab9433bfea",
        gloveOffsetX: 188,
        gloveOffsetY: 205,
        glove_id: 3,
        bat_id: 1,
        cleat_id: 1 
    }
]