module.exports = [
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "bats",
        name: "F21-PWR CRBN Fastpitch Softball Bat (-10)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f21-pwr-crbn-fastpitch-softball-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f21-pwr-crbn-fastpitch-softball-bat-1.jpeg",
        description: "Mizuno’s new 2-Piece bat utilizes a patent-pending Dual Frequency Damper™ construction to join a Black Onyx™ Carbon barrel and handle for an incredible feel. A new Detonator Cor™ technology design creates low barrel compression and a booming impact sound, giving players a smooth game-ready bat that feels great from the first swing.",
        price: "$349.99",
        age: "12, 13, 14, 15, 16",
        length: "28\", 29\", 30\", 31\", 32\"",
        whereToBuy: "https://www.mizunousa.com/product/softball-f21-pwr-crbn-10-/340551",
        uuid: "db7bfe71-2375-4223-9007-dc390243dfd4"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "bats",
        name: "F21-Titanium Fastpitch Softball Bat (-10)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f21-titanium-fastpitch-softball-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f21-titanium-fastpitch-softball-bat-1.jpeg",
        description: "High performance right out of the wrapper, the innovative F21-TITANIUM is engineered with a Hot Metal™ Titanium barrel for high-level performance. Engineered with several ground-breaking softball bat innovations, including Black Onyx Carbon™ applied throughout the bat for a lower weight and better feel. 3-Piece bat construction creates high performance with decreased vibration for a smooth feel through contact.",
        price: "$499.99",
        age: "16, 17, 18, 19, 20, 21, 22, 23, 24",
        length: "32\", 33\", 34\"",
        whereToBuy: "https://www.mizunousa.com/product/softball-f21-titanium-10-/340550",
        uuid: "09544372-c796-4997-a3d7-429e56544bfd"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "bats",
        name: "Finch Fastpitch Softball Bat (-13)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/mizuno/finch-fastpitch-softball-bat-13-inch.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/mizuno/finch-fastpitch-softball-bat-13-inch-1.jpeg",
        description: "The featured bat in Mizuno's exclusive Jennie Finch Collection.",
        price: "$120.00",
        age: "10, 11, 12, 13, 14, 15, 16",
        length: "28\", 29\", 30\", 31\", 32\"",
        whereToBuy: "https://www.mizunousa.com/ca/product/softball-finch-13/340610?isB=true",
        uuid: "ddeb2365-3152-4a7d-8ae7-91890daf9f35"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "bats",
        name: "2023 Rawlings Mantra 2.0 Fastpitch Bat (-9, -10)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/rawlings/2023-mantra-2.0-fastpitch-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/rawlings/2023-mantra-2.0-fastpitch-bat-1.jpeg",
        description: "What's your mantra? This 2023 Rawlings Mantra 2.0 Fastpitch Bat helps you bring an elite level of focus, discipline, and power with you to the plate. Crafted with an innovative three-step inner barrel, this bat perfectly balances swing speed and massive pop. Also, the 2023 Mantra features our thinnest outer barrel yet, creating unmatched trampoline on contact. The fully reconstructed F2 collar assembly creates the perfect harmony between flex and stiffness, and the ultra-light end cap makes it easy for any hitter to whip this bat through the zone.",
        price: "$399.95",
        age: "12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23",
        length: "30\", 31\", 32\", 33\", 34\"",
        whereToBuy: "https://www.rawlings.com/product/RFP3M.html",
        uuid: "36a9af16-e331-4b39-84aa-0ec6f930805b"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "bats",
        name: "Rawlings 2022 Storm T-Ball Bat (-12)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-tee-ball.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-tee-ball-1.jpeg",
        description: "This ultra-lightweight Rawlings 2022 Storm T-ball bat features a durable alloy construction. This -12 bat is approved for USA Baseball Leagues and perfect for any young t-ball player starting out at the plate. Order yours today!",
        price: "$29.95",
        age: "5, 6, 7, 8",
        length: "24\", 25\", 26\"",
        whereToBuy: "https://www.rawlings.com/product/TB2S12.html",
        uuid: "dba1f6d8-b457-41a7-9d87-49455c4d0eb5"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "bats",
        name: "Rawlings 2022 Eclipse Fastpitch Softball Bat (-12)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-eclipse-fastpitch-softball-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-eclipse-fastpitch-softball-bat-1.jpeg",
        description: "This Rawlings 2022 Eclipse fastpitch softball bat offers an extended barrel with its X-Tended sweetspot to drive more balls to the gap. The sleek black and orange design with blue accents will have you sticking out from the competition. Get your 2022 Eclipse fastpitch bat today!",
        price: "$74.95",
        age: "9, 10, 11, 12, 13, 14, 15, 16",
        length: "27\", 28\", 29\", 30\", 31\", 32\"",
        whereToBuy: "https://www.rawlings.com/product/FP2E12.html",
        uuid: "c42d7703-6d28-4433-bd46-8c510dbec745"
    },
    {
        brand: "DeMarini",
        brand_id: 6,
        category: "bats",
        name: "2022 CF (-10) Fastpitch Bat",
        image1: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-cf-10-fastpitch-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-cf-10-fastpitch-bat-1.jpg",
        description: "The 2022 DeMarini CF (-10) Fastpitch Bat Speaks for Itself. Designed to deliver a balanced swing weight and positive feedback on contact, the CF (-10) is perfect for players looking to drive the ball from gap to gap and out of the yard. The game’s top travel ball players and collegiate talent trust CF for its responsive and durable Paraflex® Plus Composite Barrel. The two-piece composite construction with a new Type-V Connection creates a great feel and directs your energy into the heart of the barrel. The lightweight composite Tracer End Cap is designed to maintain barrel integrity and optimize performance.",
        price: "$399.95",
        age: "12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23",
        length: "30\", 31\", 32\", 33\", 34\"",
        whereToBuy: "https://www.demarini.com/en-us/product/cf-fp-10-wbd2373#axis=75670",
        uuid: "57fba439-2703-4a23-ac5a-5606212f613d"
    },
    {
        brand: "DeMarini",
        brand_id: 6,
        category: "bats",
        name: "2022 CF (-9) Fastpitch Bat",
        image1: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-cf-9-fastpitch-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-cf-9-fastpitch-bat-1.jpg",
        description: "The 2022 DeMarini CF (-9) Fastpitch Bat is Loaded with Power. Stronger high school and college players looking to hit for extra bases turn to CF (-9) for its balanced yet thunderous swing. The game’s top travel ball players and collegiate talent swing CF to harness its responsive and durable Paraflex® Plus Composite Barrel. The two-piece composite construction with a new Type-V Connection creates a great feel and directs your energy into the heart of the barrel. The new ultra-strong Tremor End Cap is designed to maintain barrel power and durability so you can take big swings all year long.",
        price: "$399.95",
        age: "15, 16, 17, 18, 19, 20, 21, 22, 23",
        length: "32\", 33\", 34\"",
        whereToBuy: "https://www.demarini.com/en-us/product/cf-fp-9-wbd2376#axis=75667",
        uuid: "8903d75a-1b9c-4feb-a530-aaa9802d4432"
    },
    {
        brand: "DeMarini",
        brand_id: 6,
        category: "bats",
        name: "2022 Uprising (-12) Fastpitch Bat",
        image1: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-uprising-fastpitch-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/demarini/2022-uprising-fastpitch-bat-1.jpg",
        description: "Make an instant impact with the 2022 DeMarini Uprising (-12) Fastpitch Bat. Designed for younger players looking for a light-swinging performance bat, Uprising features a DX1™ Alloy Barrel for great pop, long-lasting durability and an easy swing. Uprising’s one-piece alloy construction allows for a stiff, responsive feel, and the Big D™ End Cap helps to reduce vibration so young hitters can swing with confidence.",
        price: "$79.99",
        age: "10, 11, 12, 13, 14, 15",
        length: "28\", 29\", 30\", 31\", 32\"",
        whereToBuy: "https://www.demarini.com/en-us/product/2022-uprising-12-fastpitch-bat-wbd2236#axis=73370",
        uuid: "61687100-823b-4115-8ef3-3cf56087a5b3"
    },
    {
        brand: "Easton",
        brand_id: 4,
        category: "bats",
        name: "2023 EASTON GHOST UNLIMITED FASTPITCH SOFTBALL BAT (-10, -9, -8)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/easton/2023-easton-ghost-unlimited-fastpitch-10-9-8.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/easton/2023-easton-ghost-unlimited-fastpitch-10-9-8-1.jpeg",
        description: "Featuring the latest in bat design innovation, the Easton 2023 Ghost Unlimited fastpitch bat is here to level up your game. As the first one-piece bat in the Ghost family, the Ghost Unlimited offers more ways to optimize your offense than ever before. ",
        price: "$499.95",
        age: "14, 15, 16, 17, 18, 19, 20",
        length: "30\", 33\", 34\"",
        whereToBuy: "https://easton.rawlings.com/product/FP23GHUL.html",
        uuid: "bf3425c7-7242-4c17-8402-bf3e567f7666"
    },
    {
        brand: "Easton",
        brand_id: 4,
        category: "bats",
        name: "2022 EASTON GHOST ADVANCED FASTPITCH BAT (-11, -10, -9, -8)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/easton/2022-easton-ghost-advanced-fastpitch-11-10-9-8.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/easton/2022-easton-ghost-advanced-fastpitch-11-10-9-8-1.jpeg",
        description: "Introducing a Ghost bat that is Advanced to the Max. The second-generation of Ghost Advanced features a Double Barrel 2 construction, combining a lighter inner barrel and stronger outer barrel, creating the lowest compression in the game for more barrel flex and Advanced Performance. The Ghost Advanced is built with all-new Sonic Comp™ Max Technology, Easton’s highest-performing and more durable composite, resulting in the iconic Ghost Advanced Sound heard across all fields. Power Boost™ Soft Knob technology provides Advanced Leverage and power potential, all while reducing vibration and improving comfort for the bottom hand. Two-piece ConneXion Evolution™ separates the handle from the barrel with the perfect amount of forgiveness and eliminated all vibration, resulting in an Advanced Feel unlike any other. Available in a -11, -10, -9, -8 models and approved for play in USA (ASA), USSSA (fastpitch only), NSA, ISA and WBSC.",
        price: "$499.95",
        age: "14, 15, 16, 17, 18, 19, 20",
        length: "30\", 31\", 32\", 33\", 34\"",
        whereToBuy: "https://easton.rawlings.com/product/FP22GHAD.html",
        uuid: "bb9a5e3d-34b9-4cd7-b377-f45d93edd7bf"
    },
    {
        brand: "Easton",
        brand_id: 4,
        category: "bats",
        name: "2022 EASTON AMETHYST FASTPITCH BAT (-11)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/easton/2022-easton-11-amethyst-fastpitch-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/easton/2022-easton-11-amethyst-fastpitch-bat-1.jpeg",
        description: "The Easton® Diamond Gem bat collection includes the Amethyst, which is crafted from ALX50™ Alloy for extended durability and balanced performance. The light swing weight and large sweet spot create power, while an ultra-thin All-Sports grip helps you keep all that power under control. If you’re ready to dominate the diamond, you’re ready to take your swings with Diamond Gem collection.",
        price: "$67.96",
        age: "9, 10, 11, 12, 13, 14, 15",
        length: "27\", 28\", 29\", 30\", 31\", 32\"",
        whereToBuy: "https://easton.rawlings.com/product/FP22AMY.html",
        uuid: "fe821c30-507e-41c0-b865-6c725648c21b"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "bats",
        name: "F22-FINCH YOUTH TEE BALL SOFTBALL BAT (-13)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f22-finch-youth-tee-bal-softball-bat.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/mizuno/f22-finch-youth-tee-bal-softball-bat-1.jpeg",
        description: "The featured tee-ball bat in Mizuno's exclusive Jennie Finch Collection. Created with the beginner softball player’s specific needs in focus and designed to be powerful, comfortable, and lightweight. Features MZ-1300 Alloy for power and an extremely lightweight design that does not compromise durability. Our Speed Helix™ Grip adds comfort and a soft feel. One Year Warranty.",
        price: "$60.00",
        age: "4, 5, 6, 7, 8",
        length: "24\", 25\", 26\"",
        whereToBuy: "https://www.mizunousa.com/ca/product/softball-finch-tee-ball-13/340611?isB=true",
        uuid: "0eb65ec1-281e-4842-877d-99dd0218513a"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "bats",
        name: "Quatro Pro College/High School Softball Bat (-10)",
        image1: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-quatro-pro-fastpitch.png",
        image2: "https://equipmeserver.herokuapp.com/images/bats/rawlings/rawlings-quatro-pro-fastpitch-1.jpeg",
        description: "Get more pop, more distance and a faster, lighter swing speed with the all new Quatro Pro - a collision of our best technologies. The redesign of the Q4 technology features a newly constructed inner barrel yielding a larger sweet spot and a faster, more balanced swing for optimal offense. #RawlingsSoftball",
        price: "$349.95",
        age: "14, 15, 16, 17, 18, 19, 20+",
        length: "30\", 31\", 32\", 33\", 34\"",
        whereToBuy: "https://www.rawlings.com/product/FPQP10.html",
        uuid: "ffd26156-2346-451f-923a-64f28c3fd3c7"
    }
];