module.exports = [
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Classic Pro Soft Baseball First Base Mitt 12.5\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-classic-pro-soft-baseball-first-base-12.5.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno/mizuno-classic-pro-soft-baseball-first-base-12.5-1.jpeg",
        price: "$229.99",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First Base, Catcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf28s3-classic-pro-soft-fbm/312746",
        uuid: "29f8590d-613a-426b-b8cf-bee42346e758"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball First Base Mitt 12.5\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-first-base-12.5.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-first-base-12.5-1.jpeg",
        price: "$150.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First Base, Catcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf90b4-franchise-fbm-12-5/312973",
        uuid: "b892195f-580f-4c4d-a276-294b95057596"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Infield Glove 11.75\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-infield-glove-11.75.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-infield-glove-11.75-1.jpeg",
        price: "$120.00",
        size: "11.75\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Infield",
        sport:"Baseball",
        left: "no",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1175b4-franchise-11-75in/312957",
        uuid: "78eb88e6-e376-4c9f-998f-fe4c1145bee9"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Outfield Glove 12.5\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5-1.jpeg",
        price: "$120.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1250b4-franchise-12-5in/312959",
        uuid: "9159816a-f924-404d-8ba9-bcc46b13d4d4"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Outfield Glove 12.5\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5-A.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno//mizuno-franchise-series-baseball-outfield-12.5-A-1.jpeg",
        price: "$109.99",
        size: "12.5\"",
        pocket: "Open",
        color: "Coffee",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1250b3-franchise/312629",
        uuid: "8e97247d-5ec4-45ae-8610-3e3b6254b217"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Pitcher/Outfield Baseball Glove 12\"",
        image1: "http://localhost:8080/images/gloves/mizuno/mizuno-franchise-series-baseball-pitcher-outfield-glove-12.jpeg",
        image2: "http://localhost:8080/images/gloves/mizuno//mizuno-franchise-series-baseball-pitcher-outfield-glove-12-1.jpeg",
        price: "$120.00",
        size: "12\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Pitcher, Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1200b4-franchise-12in/312958",
        uuid: "df0b1eed-296a-4095-adaf-5eace2aba514"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2023 A2K® 1787 11.75\" INFIELD BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2023-a2k-1787-11.75-infield-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2023-a2k-1787-11.75-infield-baseball-glove-1.jpeg",
        price: "$399.95",
        size: "11.75\"",
        pocket: "Open",
        color: "Brown",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2023-a2k-1787-wbw101271#throwinghand=52622&size=52586",
        uuid: "8cfbc362-9e43-4a0f-8ae6-931bdb874163"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A2000 SCDP15SS 11.5\" INFIELD BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2022-a2000-scdp15ss-11.5-infield-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2022-a2000-scdp15ss-11.5-infield-baseball-glove-1.jpeg",
        price: "$299.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Black",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a2000-scdp15ss-11-5-infield-baseball-glove-wbw101003#throwinghand=52622&size=52766",
        uuid: "9a24c527-61b4-4640-8af0-f64b11437fe4"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2021 A2K 1799SS 12.75\" OUTFIELD BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2021-a2k-1799ss-12.75-outfield-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2021-a2k-1799ss-12.75-outfield-baseball-glove-1.jpeg",
        price: "$379.95",
        size: "12.75\"",
        pocket: "Open",
        color: "Black",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2021-a2k-1799ss-12-75-outfield-baseball-glove-wbw100663#throwinghand=52622&size=52619",
        uuid: "29e4c192-4514-4edd-b469-1e57220b9d2e"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A1000 DP15 11.5\" INFIELD BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2022-a1000-dp15-11.5-infield-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2022-a1000-dp15-11.5-infield-baseball-glove-1.jpeg",
        price: "$149.99",
        size: "11.5\"",
        pocket: "Open",
        color: "Black",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a1000-dp15-11-5-infield-baseball-glove-wbw100729#throwinghand=52622&size=52766",
        uuid: "9389148a-3f0e-4074-a699-2e114a7a3c97"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2021 A2000 B2 12\" PITCHER'S BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2021-a2000-b2-12-pitchers-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2021-a2000-b2-12-pitchers-baseball-glove-1.jpeg",
        price: "$299.95",
        size: "12\"",
        pocket: "Closed",
        color: "Red",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2021-a2000-b2-12-pitcher-s-baseball-glove-wbw100890#throwinghand=52622&size=53072",
        uuid: "757a6ff5-1a98-4296-a29c-3f145bed5e5a"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A700 12.5\" OUTFIELD BASEBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/wilson/2022-a700-12.5-outfield-baseball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/wilson/2022-a700-12.5-outfield-baseball-glove-1.jpeg",
        price: "$89.95",
        size: "12.5\"",
        pocket: "Open",
        color: "Black",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a700-12-5-outfield-baseball-glove-wbw100724#throwinghand=52622&size=52694",
        uuid: "75d16f8d-f06f-45bc-85b6-f5b3921663b7"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 EXCLUSIVE HEART OF THE HIDE R2G 11.5\" I-WEB GLOVE",
        image1: "http://localhost:8080/images/gloves/rawlings/2021-exclusive-heart-of-the-hide-r2g-11.5-i-web-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/2021-exclusive-heart-of-the-hide-r2g-11.5-i-web-glove-1.jpeg",
        price: "$279.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Blue, Red",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/RSGPROR204W-2CBS.html",
        uuid: "851e4e1e-3397-4053-9a15-68ddd9540f6d"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 HEART OF THE HIDE 11.5\" I-WEB INFIELD GLOVE",
        image1: "http://localhost:8080/images/gloves/rawlings/2021-heart-of-the-hide-11.5-i-web-infield-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/2021-heart-of-the-hide-11.5-i-web-infield-glove-1.jpeg",
        price: "$299.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PRONP4-2CB.html",
        uuid: "11626324-19e4-4fd7-90e6-3af4e0802b12"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "PLAYERS SERIES 10\" BASEBALL/SOFTBALL GLOVE",
        image1: "http://localhost:8080/images/gloves/rawlings/players-series-10-baseball-softball-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/players-series-10-baseball-softball-glove-1.jpeg",
        price: "$22.95",
        size: "10\"",
        pocket: "Closed",
        color: "Black",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "no",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/P-PL10BMT.html",
        uuid: "08cf2087-33ce-4a0f-8e78-7b1fd8187682"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 Exclusive HOH R2G 12.75-Inch Outfield Glove",
        image1: "http://localhost:8080/images/gloves/rawlings/2021-exclusive-hoh-r2g-12.75-outfield-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/2021-exclusive-hoh-r2g-12.75-outfield-glove-1.jpeg",
        price: "$299.95",
        size: "12.75\"",
        pocket: "Open",
        color: "Black, Blue",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PROR3319-6NCB.html",
        uuid: "31c7dd34-459d-461c-a85a-27ab9433bfea"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2022 GERRIT COLE PRO PREFERRED INFIELD/PITCHER'S GLOVE",
        image1: "http://localhost:8080/images/gloves/rawlings/2022-gerrit-cole-pro-perferred-infield-pitchers-glove.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/2022-gerrit-cole-pro-perferred-infield-pitchers-glove-1.jpeg",
        price: "$379.95",
        size: "12.25\"",
        pocket: "Closed",
        color: "Black",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PROR3319-6NCB.html",
        uuid: "b24189ad-e804-4c42-b3b1-338eb73b82ec"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2022 HEART OF THE HIDE R2G 12.5-INCH FIRST BASE MITT",
        image1: "http://localhost:8080/images/gloves/rawlings/2022-heart-of-the-hide-r2g-12.5-inch-first-base-mitt.jpeg",
        image2: "http://localhost:8080/images/gloves/rawlings/2022-heart-of-the-hide-r2g-12.5-inch-first-base-mitt-1.jpeg",
        price: "$299.95",
        size: "12.5\"",
        pocket: "Open",
        color: "Blonde, Black",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/P-PRORFM18-10BC.html",
        uuid: "a2c324f6-96ef-44fc-ac9c-9904f24da22a"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "Alpha™ S-1150 11.5\" I-Web Infield",
        image1: "http://localhost:8080/images/gloves/nokona/alpha-s-11.5-inch-i-web-infield.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/alpha-s-11.5-inch-i-web-infield-1.jpeg",
        price: "$400.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde, Brown",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/s-1150-11-5-i-web-infield/",
        uuid: "ef8c3975-be23-4ee6-83d4-711c600d2892"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "X2 Elite™ X2-V1250 Velcro 12.5\" Closed Web Infield/Outfield",
        image1: "http://localhost:8080/images/gloves/nokona/X2-elite-v1250-velcro-closed-web-pitcher.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/X2-elite-v1250-velcro-closed-web-pitcher-1.jpeg",
        price: "$450.00",
        size: "12.5\"",
        pocket: "Closed",
        color: "Brown",
        position: "Pitcher",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/x2-v1250-velcro-12-5-closed-web-infield-outfield/",
        uuid: "60bd57fe-899d-4ffa-8315-2398d72e7a7f"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "AmericanKIP™ A-1150-Blonde 11.5\" I Web Infield",
        image1: "http://localhost:8080/images/gloves/nokona/americanKIP-a-1150-blonde-11.5-i-web-infield.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/americanKIP-a-1150-blonde-11.5-i-web-infield-1.jpeg",
        price: "$425.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/a-1150-blonde-11-5-i-web-infield/",
        uuid: "577fab72-25d9-4e8f-b4c6-e25142087ec7"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "AmericanKIP™ A-V1250-Navy Velcro 12.5\" Outfield",
        image1: "http://localhost:8080/images/gloves/nokona/americanKIP-a-v1250-navy-12.5-outfield.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/americanKIP-a-v1250-navy-12.5-outfield-1.jpeg",
        price: "$425.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Blue",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/a-v1250-navy-velcro-12-5-infield-outfield/",
        uuid: "11ad714f-c862-4589-a069-8fd669d6aea9"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "Alpha™ S-3 12.5\" H-Web First Base Mitt",
        image1: "http://localhost:8080/images/gloves/nokona/alpha-s-3-12.5-h-web-first-base-mitt.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/alpha-s-3-12.5-h-web-first-base-mitt-1.jpeg",
        price: "$400.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First Base, Catcher",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/s-3-12-5-h-web-first-base-mitt/",
        uuid: "e74b708f-8b62-4fbb-b6be-6d0dbb3cd806"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "\"Made in Texas\" PL-1200 12\" Modified Trap Infield/Outfield",
        image1: "http://localhost:8080/images/gloves/nokona/made-in-texas-pl-1200-modified-trap-infield-outfield.jpeg",
        image2: "http://localhost:8080/images/gloves/nokona/made-in-texas-pl-1200-modified-trap-infield-outfield-1.jpeg",
        price: "$400.00",
        size: "12\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Infield, Outfield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/made-in-texas-pl-1200-12-closed-web-infield-outfield/",
        uuid: "e4b0cb63-532a-4143-946d-9e5634129125"
    }
];