module.exports = [
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Classic Pro Soft Baseball First Base Mitt 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-classic-pro-soft-baseball-first-base-12.5.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-classic-pro-soft-baseball-first-base-12.5-1.jpeg",
        description: "The Classic Pro Soft series is handcrafted with Throwback Leather, which is a rugged, rich and naturally pre-oiled leather that breaks in quickly and retains its shape over time. Featuring professional patterns designed for the best players in the world and UltraSoft Pro Palm Liner for an unmatched feel that makes Classic Pro Soft such a highly-rated glove choice.",
        price: "$229.99",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First base, Catcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf28s3-classic-pro-soft-fbm/312746",
        uuid: "29f8590d-613a-426b-b8cf-bee42346e758"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball First Base Mitt 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-first-base-12.5.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-first-base-12.5-1.jpeg",
        description: "Mizuno Franchise Gloves are constructed using comfortable, hand-based patterns, which set your pocket under the web, allowing you to shape your glove like a pro. Pre-oiled full grain leather maintains durability and provides a soft, game-ready feel.",
        price: "$150.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First base, Catcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf90b4-franchise-fbm-12-5/312973",
        uuid: "b892195f-580f-4c4d-a276-294b95057596"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Infield Glove 11.75\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-infield-glove-11.75.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-infield-glove-11.75-1.jpeg",
        description: "Mizuno Franchise Gloves are constructed using comfortable, hand-based patterns, which set your pocket under the web, allowing you to shape your glove like a pro. Full grain leather maintains durability and provides a soft, game-ready feel.",
        price: "$120.00",
        size: "11.75\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Infield",
        sport:"Baseball",
        left: "no",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1175b4-franchise-11-75in/312957",
        uuid: "78eb88e6-e376-4c9f-998f-fe4c1145bee9"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Outfield Glove 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5-1.jpeg",
        description: "Mizuno Franchise Gloves are constructed using comfortable, hand-based patterns, which set your pocket under the web, allowing you to shape your glove like a pro. Full grain leather maintains durability and provides a soft, game-ready feel.",
        price: "$120.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1250b4-franchise-12-5in/312959",
        uuid: "9159816a-f924-404d-8ba9-bcc46b13d4d4"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Baseball Outfield Glove 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5-A.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-outfield-12.5-A-1.jpeg",
        description: "Mizuno Franchise Gloves are constructed using comfortable, hand-based patterns, which set your pocket under the web, allowing you to shape your glove like a pro.  Pre-oiled java leather maintains durability and provides a soft, game-ready feel.",
        price: "$109.99",
        size: "12.5\"",
        pocket: "Open",
        color: "Coffee",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1250b3-franchise/312629",
        uuid: "8e97247d-5ec4-45ae-8610-3e3b6254b217"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Franchise Series Pitcher/Outfield Baseball Glove 12\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-pitcher-outfield-glove-12.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-franchise-series-baseball-pitcher-outfield-glove-12-1.jpeg",
        description: "Mizuno Franchise Gloves are constructed using comfortable, hand-based patterns, which set your pocket under the web, allowing you to shape your glove like a pro. Full grain leather maintains durability and provides a soft, game-ready feel.",
        price: "$120.00",
        size: "12\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Pitcher, Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gfn1200b4-franchise-12in/312958",
        uuid: "df0b1eed-296a-4095-adaf-5eace2aba514"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRO SELECT BASEBALL FIRST BASE MITT 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-select-baseball-first-base-mitt-12.5.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-select-baseball-first-base-mitt-12.5-1.jpeg",
        description: "Mizuno Pro Select combines the rich heritage of the Mizuno Pro series with advanced glove scans of hundreds of professionals to create pocket designs tailored specifically to each position and how players prefer to break-in their glove. This unique approach to glove design allows for all players to shape their glove like a pro for an incredibly natural fit and feel. Made with top-quality US Steerhide leather that is firm, incredibly durable, and will form to your hand perfectly as you break it in.",
        price: "$449.99",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First base, Catcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gps1-300fbm-pro-select-12-5in/312596",
        uuid: "50a967d5-6741-45c1-ae57-d9cd6f7712ad"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2023 A2K® 1787 11.75\" INFIELD BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2023-a2k-1787-11.75-infield-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2023-a2k-1787-11.75-infield-baseball-glove-1.jpeg",
        description: "Timeless. The 2023 A2K 1787 boasts flawless Vintage Tan Pro Stock® Select leather with Black laces to deliver an everlasting look on the infield dirt. This A2K checks in at 11.75” to seize line drives at second base or backhand scorching grounders down the third base line. Sorted and scrutinized three times to ensure its perfection, the Pro Stock® Select leather in Vintage Tan offers unprecedented durability and immaculate feel, and Double Palm Construction allows the player to break in and shape the glove to their preferences. Bold Logos outlined in Black ensure the A2K 1787 will draw everyone’s attention.",
        price: "$399.95",
        size: "11.75\"",
        pocket: "Open",
        color: "Brown",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2023-a2k-1787-wbw101271#throwinghand=52622&size=52586",
        uuid: "8cfbc362-9e43-4a0f-8ae6-931bdb874163"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A2000 SCDP15SS 11.5\" INFIELD BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a2000-scdp15ss-11.5-infield-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a2000-scdp15ss-11.5-infield-baseball-glove-1.jpeg",
        description: "Designed for young players and middle infielders with smaller hands, the iconic 2022 A2000® SCDP15SS features Pedroia Fit construction with a narrower wrist opening and shorter finger stalls. Spin Control Technology™ on the Black Pro Stock® leather palm and H-Web increases friction between the ball and the glove, allowing for sure outs and quick transfers. The Black SuperSkin™ reduces glove weight while improving durability, and Blonde laces and binding tie it all together.",
        price: "$299.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Black",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a2000-scdp15ss-11-5-infield-baseball-glove-wbw101003#throwinghand=52622&size=52766",
        uuid: "9a24c527-61b4-4640-8af0-f64b11437fe4"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2021 A2K 1799SS 12.75\" OUTFIELD BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2021-a2k-1799ss-12.75-outfield-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2021-a2k-1799ss-12.75-outfield-baseball-glove-1.jpeg",
        description: "The A2K® 1799SS brings together Black Pro Stock Select Leather and Saddle Tan SnakeSkin Pro Stock Select Leather with lightweight, but durable Black SuperSkin. At 12.75\", big leaguers favor this glove for its incredible length and deep pocket. The reinforced Dual Post Web keeps the pocket in great condition well after it's broken in, so you can roam the outfield for years to come.",
        price: "$379.95",
        size: "12.75\"",
        pocket: "Open",
        color: "Black",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2021-a2k-1799ss-12-75-outfield-baseball-glove-wbw100663#throwinghand=52622&size=52619",
        uuid: "29e4c192-4514-4edd-b469-1e57220b9d2e"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A1000 DP15 11.5\" INFIELD BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a1000-dp15-11.5-infield-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a1000-dp15-11.5-infield-baseball-glove-1.jpeg",
        description: "Take full control with the A1000® DP15 11.5” Infield Glove, the ball glove with a narrower wrist opening and shorter finger stalls to create a secure fit for players with smaller hands. Tropical Blue Outlined Logos pop against the Black Full Grain leather, and the H-Web and shallow pocket make transfers a breeze.",
        price: "$149.99",
        size: "11.5\"",
        pocket: "Open",
        color: "Black",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a1000-dp15-11-5-infield-baseball-glove-wbw100729#throwinghand=52622&size=52766",
        uuid: "9389148a-3f0e-4074-a699-2e114a7a3c97"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2021 A2000 B2 12\" PITCHER'S BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2021-a2000-b2-12-pitchers-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2021-a2000-b2-12-pitchers-baseball-glove-1.jpeg",
        description: "Keep hitters guessing with the A2000® B2. A Closed Two-Piece Web allows you to change grips and keep the ball hidden on the mound, and the 12” length is a perfect size to make plays on ground balls and comebackers. Copper Pro Stock® Leather with Black accents and Yellow Bold Logos offer an eye-catching look, and the ComfortPro Fit of this B2 will form to the shape of your hand with use, creating a glove that was made for you.",
        price: "$299.95",
        size: "12\"",
        pocket: "Closed",
        color: "Red",
        position: "Pitcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2021-a2000-b2-12-pitcher-s-baseball-glove-wbw100890#throwinghand=52622&size=53072",
        uuid: "757a6ff5-1a98-4296-a29c-3f145bed5e5a"
    },
    {
        brand: "Wilson",
        brand_id: 3,
        category: "gloves",
        name: "2022 A700 12.5\" OUTFIELD BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a700-12.5-outfield-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/wilson/2022-a700-12.5-outfield-baseball-glove-1.jpeg",
        description: "Go after fly balls on the outfield grass with the A700 12.5” Outfield Glove. Black and Blonde Full Grain leather with a sturdy Single Post & 3 Bar Web is game ready on day one.",
        price: "$89.95",
        size: "12.5\"",
        pocket: "Open",
        color: "Black",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.wilson.com/en-us/product/2022-a700-12-5-outfield-baseball-glove-wbw100724#throwinghand=52622&size=52694",
        uuid: "75d16f8d-f06f-45bc-85b6-f5b3921663b7"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 EXCLUSIVE HEART OF THE HIDE R2G 11.5\" I-WEB GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-exclusive-heart-of-the-hide-r2g-11.5-i-web-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-exclusive-heart-of-the-hide-r2g-11.5-i-web-glove-1.jpeg",
        description: "Meticulously crafted from ultra-premium steer-hide leather, the 2021 exclusive Heart of the Hide R2G I-web glove offers superior quality and performance. We've constructed all of our HOH R2G gloves with an additional 25% break-in too, so they're ready-to-go out of the box! As a result, you get the same renowned feel and durability expected from any HOH glove - with a more game-ready feel. ",
        price: "$279.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Blue, Red",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/RSGPROR204W-2CBS.html",
        uuid: "851e4e1e-3397-4053-9a15-68ddd9540f6d"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 HEART OF THE HIDE 11.5\" I-WEB INFIELD GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-heart-of-the-hide-11.5-i-web-infield-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-heart-of-the-hide-11.5-i-web-infield-glove-1.jpeg",
        description: "The 2021 Heart of the Hide 11.5-inch I-web glove is constructed from ultra-premium steer-hide leather. Our HOH leather is world-renowned for its unmatched quality. It also breaks in to form the perfect pocket for you. Its NP-pattern is a popular choice for infielders, thanks to it's wide, flat pocket that promotes quick transfers up the middle.",
        price: "$299.95",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PRONP4-2CB.html",
        uuid: "11626324-19e4-4fd7-90e6-3af4e0802b12"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "PLAYERS SERIES 10\" BASEBALL/SOFTBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/players-series-10-baseball-softball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/players-series-10-baseball-softball-glove-1.jpeg",
        description: "The Players Series 10-Inch baseball/softball glove is constructed with a soft, pliable shell for easy close and control. Add the eye-catching accents, soft inner linings, and our signature Rawlings script and your young athlete has the perfect blend of style and function to kick off their career. Recommended for ages 5-7. Order yours today!",
        price: "$22.95",
        size: "10\"",
        pocket: "Closed",
        color: "Black",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "no",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/P-PL10BMT.html",
        uuid: "08cf2087-33ce-4a0f-8e78-7b1fd8187682"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2021 Exclusive HOH R2G 12.75-Inch Outfield Glove",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-exclusive-hoh-r2g-12.75-outfield-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2021-exclusive-hoh-r2g-12.75-outfield-glove-1.jpeg",
        description: "Hit the field right away with the 2021 exclusive HOH R2G 12.75-inch outfield glove. It was meticulously crafted from ultra-premium steer-hide leather to help you perform your best. Like every R2G glove, we've added an additional 25% factory break-in to offer a more game-ready feel too. As a result, you'll be able to use it right out of the box, making it perfect for any player who wants an easy break-in process.",
        price: "$299.95",
        size: "12.75\"",
        pocket: "Open",
        color: "Black, Blue",
        position: "Outfield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PROR3319-6NCB.html",
        uuid: "31c7dd34-459d-461c-a85a-27ab9433bfea"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2022 GERRIT COLE PRO PREFERRED INFIELD/PITCHER'S GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2022-gerrit-cole-pro-perferred-infield-pitchers-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2022-gerrit-cole-pro-perferred-infield-pitchers-glove-1.jpeg",
        description: "Hit the field right away with the 2021 exclusive HOH R2G 12.75-inch outfield glove. It was meticulously crafted from ultra-premium steer-hide leather to help you perform your best. Like every R2G glove, we've added an additional 25% factory break-in to offer a more game-ready feel too. As a result, you'll be able to use it right out of the box, making it perfect for any player who wants an easy break-in process.",
        price: "$379.95",
        size: "12.25\"",
        pocket: "Closed",
        color: "Black",
        position: "Pitcher",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/PROR3319-6NCB.html",
        uuid: "b24189ad-e804-4c42-b3b1-338eb73b82ec"
    },
    {
        brand: "Rawlings",
        brand_id: 2,
        category: "gloves",
        name: "2022 HEART OF THE HIDE R2G 12.5-INCH FIRST BASE MITT",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2022-heart-of-the-hide-r2g-12.5-inch-first-base-mitt.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/rawlings/2022-heart-of-the-hide-r2g-12.5-inch-first-base-mitt-1.jpeg",
        description: "Take off the tags, and hit the field with the 2022 Heart of the Hide R2G 12.5-inch first base mitt. It was meticulously crafted from ultra-premium steer-hide leather, and comes with an additional 25% factory break-in for a more game-ready feel. As a result, this HOH R2G first base mitt will quickly form the perfect pocket so you can spend less time breaking it in and more time on the field!",
        price: "$299.95",
        size: "12.5\"",
        pocket: "Open",
        color: "Blonde, Black",
        position: "First base",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.rawlings.com/product/P-PRORFM18-10BC.html",
        uuid: "a2c324f6-96ef-44fc-ac9c-9904f24da22a"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "Alpha™ S-1150 11.5\" I-Web Infield",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/alpha-s-11.5-inch-i-web-infield.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/alpha-s-11.5-inch-i-web-infield-1.jpeg",
        description: "The Alpha™ series is created with virtually no break-in needed, and has now been upgraded with AmericanKIP™ and SuperSoft™ leathers for the ultimate combination of game-readiness and durability. This mix of leathers provides a lighter-weight glove that is even more game-ready and has a softer feel, while the palm leather makes the Alpha™ very durable. A position-specific, light-weight, durable, high-performing baseball and softball series for all ages.",
        price: "$400.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde, Brown",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/s-1150-11-5-i-web-infield/",
        uuid: "ef8c3975-be23-4ee6-83d4-711c600d2892"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "X2 Elite™ X2-V1250 Velcro 12.5\" Closed Web Infield/Outfield",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/X2-elite-v1250-velcro-closed-web-pitcher.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/X2-elite-v1250-velcro-closed-web-pitcher-1.jpeg",
        description: "Nokona’s elite performance, ready-for-play, position-specific series. The X2 Elite™ is made with Nokona’s proprietary top-grain Stampede™ Steerhide and Kangaroo leathers, for a light-weight and game-ready glove. The perfect combination of top quality and high performance.",
        price: "$450.00",
        size: "12.5\"",
        pocket: "Closed",
        color: "Brown",
        position: "Pitcher",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/x2-v1250-velcro-12-5-closed-web-infield-outfield/",
        uuid: "60bd57fe-899d-4ffa-8315-2398d72e7a7f"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "AmericanKIP™ A-1150-Blonde 11.5\" I Web Infield",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/americanKIP-a-1150-blonde-11.5-i-web-infield.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/americanKIP-a-1150-blonde-11.5-i-web-infield-1.jpeg",
        description: "Introducing the AmericanKIP™ series, made with the finest American steerhide, tanned to create a leather with similar characteristics to Japanese and European 'kip' leather, making a light-weight and highly structured glove.  This series is offered in four modern colors - white, black, blonde, and gray - and is a top choice among our pro players.",
        price: "$425.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Blonde",
        position: "Infield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/a-1150-blonde-11-5-i-web-infield/",
        uuid: "577fab72-25d9-4e8f-b4c6-e25142087ec7"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "AmericanKIP™ A-V1250-Navy Velcro 12.5\" Outfield",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/americanKIP-a-v1250-navy-12.5-outfield.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/americanKIP-a-v1250-navy-12.5-outfield-1.jpeg",
        description: "Introducing the AmericanKIP™ series, made with the finest American steerhide, tanned to create a leather with similar characteristics to Japanese and European 'kip' leather, making a light-weight and highly structured glove.  This series is offered in four modern colors - white, black, blonde, navy and gray - and is a top choice among our pro players.",
        price: "$425.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Blue",
        position: "Outfield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/a-v1250-navy-velcro-12-5-infield-outfield/",
        uuid: "11ad714f-c862-4589-a069-8fd669d6aea9"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "Alpha™ S-3 12.5\" H-Web First Base Mitt",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/alpha-s-3-12.5-h-web-first-base-mitt.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/alpha-s-3-12.5-h-web-first-base-mitt-1.jpeg",
        description: "The Alpha™ series is created with virtually no break-in needed, and has now been upgraded with AmericanKIP™ and SuperSoft™ leathers for the ultimate combination of game-readiness and durability. This mix of leathers provides a lighter-weight glove that is even more game-ready and has a softer feel, while the palm leather makes the Alpha™ very durable. A position-specific, light-weight, durable, high-performing baseball and softball series for all ages.",
        price: "$400.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "First base, Catcher",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/s-3-12-5-h-web-first-base-mitt/",
        uuid: "e74b708f-8b62-4fbb-b6be-6d0dbb3cd806"
    },
    {
        brand: "Nokona",
        brand_id: 5,
        category: "gloves",
        name: "\"Made in Texas\" PL-1200 12\" Modified Trap Infield/Outfield",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/nokona/made-in-texas-pl-1200-modified-trap-infield-outfield.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/nokona/made-in-texas-pl-1200-modified-trap-infield-outfield-1.jpeg",
        description: "A true baseball leather for true baseball players.  By combining Stampede Leather with rigid Sandstone Leather, we have given this series the best of everything.  Lined with Stampede, this glove feels great right from shelf.  The Sandstone Leather provides the shape and rigidity baseball players demand.\"Made in Texas\" embroidered on the thumb. For players looking for a sturdy glove that is form fitting and moldable.",
        price: "$400.00",
        size: "12\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Infield, Outfield",
        sport: "Baseball, Softball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://nokona.com/product/made-in-texas-pl-1200-12-closed-web-infield-outfield/",
        uuid: "e4b0cb63-532a-4143-946d-9e5634129125"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRO ANDRELTON SIMMONS 11.5\" BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-andrelton-simmons-11.5.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-andrelton-simmons-11.5-1.jpeg",
        description: "The glove model of Andrelton Simmons, the Mizuno Pro series features the highest quality leather and raw materials available in the world. Designed by our finest Master Craftsmen who eat, sleep, and breathe glove design and have dedicated their lives to the pursuit of the perfect pattern. Utilizing the glove scans of hundreds of professional players, each Mizuno Pro model is created with a perfect, already-formed pocket based on players’ needs and preferences at each position. Made with US Kip leather tanned in Japan to give you a soft, yet firm feel that will form just the way you like it and hold up to the speed of the game so that you can perform at your highest level.",
        price: "$550.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Red, Blue",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gmp2as-400s-mizuno-pro-11-50/312908",
        uuid: "27e29b04-372c-4f55-b058-65ff0e0f6fa4"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRIME ELITE PITCHER FASTPITCH SOFTBALL GLOVE 12\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prime-elite-pitcher-fastpitch-softball-glove-12.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prime-elite-pitcher-fastpitch-softball-glove-12-1.jpeg",
        description: "The new Mizuno Prime Elite series is crafted with soft, smooth, white and grey colored leather that is durable with a premium feel. Featuring an UltraSoft Pro Palm Liner for a soft feel and finish. A perforated thumb and pinky panel design reduces weight and increases breathability. Created with Finger Core technology, which is a new finger stall shape that helps improve flexibility and control when making a tough play, while also providing a more comfortable option for players who prefer to shift their ring finger to the pinky slot. Designed with Fastpitch patterns to make Prime Elite an excellent glove choice for serious players wanting to compete at their highest level on the field.",
        price: "$230.00",
        size: "12\"",
        pocket: "Open",
        color: "White, Grey",
        position: "Pitcher",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/softball-gpe1200f1-prime-elite-fp-12/312913",
        uuid: "807fa05c-4a54-4d59-9b87-3e7a9de88db9"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRO BRETT GARDNER 12.75\" BASEBALL GLOVE",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-brett-gardner-12.75-baseball-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-brett-gardner-12.75-baseball-glove-1.jpeg",
        description: "The glove model of Brett Gardner, the Mizuno Pro series features the highest quality leather and raw materials available in the world. Designed by our finest Master Craftsmen who eat, sleep, and breathe glove design and have dedicated their lives to the pursuit of the perfect pattern. Utilizing the glove scans of hundreds of professional players, each Mizuno Pro model is created with a perfect, already-formed pocket based on players’ needs and preferences at each position. Made with US Kip leather tanned in Japan to give you a soft, yet firm feel that will form just the way you like it and hold up to the speed of the game so that you can perform at your highest level.",
        price: "$550.00",
        size: "12.75\"",
        pocket: "Open",
        color: "Black",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gmp2bg-700ds-mizuno-pro-12-75/312984",
        uuid: "e09c097b-3d92-49ac-88ee-33b7608d8b85"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRO INFIELD BASEBALL GLOVE 11.5\" - REGULAR POCKET",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-infield-baesball-glove-11.5-regular-pocket.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-infield-baesball-glove-11.5-regular-pocket-1.jpeg",
        description: "The Mizuno Pro series features the highest quality leather and raw materials available in the world. Designed by our finest Master Craftsmen, who eat, sleep, and breathe glove design and have dedicated their lives to the pursuit of the perfect pattern. Utilizing the glove scans of hundreds of professional players, each Mizuno Pro model is created with a perfect, already-formed pocket based players’ needs and preferences at each position. Made with US Kip leather tanned in Japan to give you a soft, yet firm feel that will form just the way you like it and hold up to the speed of the game so that you can perform at your highest level.",
        price: "$499.99",
        size: "11.5\"",
        pocket: "Open",
        color: "Black, Blonde",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gmp2bk-400rdd3-mizuno-pro-11-5/312838",
        uuid: "e4341bef-8bdb-4f78-bad7-108061481753"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRO LIMITED EDITION INFIELD BASEBALL GLOVE 11.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-limited-edition-infield-glove-11.5.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-pro-limited-edition-infield-glove-11.5-1.jpeg",
        description: "Made in Haga, Japan: The glove of choice for over 100 professional ballplayers, each Mizuno Pro LE is meticulously handcrafted by one of the most revered Glove Craftsman in the world—a Mizuno Glove Master. Mizuno Pro LE gloves are made with Northern European Kip leather, which is hand-selected and impeccably conditioned. Regarded as the finest ball glove leather available. Mizuno Pro LE is the only glove with its own reconditioning program in which we will repair and recondition your glove once during its lifetime to restore it to its original glory.",
        price: "$699.99",
        size: "11.5\"",
        pocket: "Open",
        color: "Brown",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gmp400j-mizuno-pro/312378",
        uuid: "307a1f60-c2a2-4ed5-bcf0-0666fc7152ad"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "MVP PRIME BASEBALL FIRST BASE MITT 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-mvp-prime-baseball-first-base-mitt-12.5.png",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-mvp-prime-baseball-first-base-mitt-12.5-1.png",
        description: "The Mizuno MVP Prime series is made for ballplayers striving to get to the next level. Featuring Center Pocket Designed Patterns that naturally center the pocket under the index finger for the most versatile break-in possible. Handcrafted with Bio Soft Leather, which is a professional style smooth leather that has the perfect balance of oil and softness for exceptional feel and firm control that serious players demand.",
        price: "$190.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Black, Cherry",
        position: "First base",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf50b3bc/312881",
        uuid: "684912b1-e1b7-41fb-8d8b-11cb2342574d"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PROSPECT SERIES POWERCLOSE™ BASEBALL GLOVE 10\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prospect-series-poerclose-baeball-glove-10.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prospect-series-poerclose-baeball-glove-10-1.jpeg",
        description: "Mizuno Prospect Series uses full grain pigskin leather, providing great durability and  enhanced softness. Pioneered and perfected by Mizuno, PowerClose™ Technology makes catching significantly easier to help your Prospect learn to love the game. It's not a perfect first glove unless you see the PowerClose™ stamp.",
        price: "$55.00",
        size: "10\"",
        pocket: "Open",
        color: "Black, red",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gpp1000y3rd-prospect-rd-10/312721?isB=true",
        uuid: "b448ce1b-0b9f-4892-845d-9492ce5fc40f"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PRIME ELITE INFIELD BASEBALL GLOVE 11.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prime-elite-infield-baseball-glove-11.5.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prime-elite-infield-baseball-glove-11.5-1.jpeg",
        description: "The new Mizuno Prime Elite series is crafted with soft, smooth, mahogany-colored leather that is durable with a pro-level feel. Featuring an UltraSoft Pro Palm Liner for a soft feel and finish. A perforated thumb and pinky panel design reduces weight and increases breathability. Designed with Pro patterns to make Prime Elite an excellent glove choice for serious players wanting to compete at their highest level on the field.",
        price: "$230.00",
        size: "11.5\"",
        pocket: "Open",
        color: "Brown",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gpe1150m-prime-elite-11-5/312875",
        uuid: "7a5803c3-811b-486a-afd3-503cb10f8c62"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PROSPECT SELECT YOUTH SERIES INFIELD BASEBALL GLOVE 11\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/prospect-select-series-infield-baseball-glove-11.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/prospect-select-series-infield-baseball-glove-11-1.jpeg",
        description: "Mizuno Prospect Select offers the youth player a full grain leather glove, providing the same high end look and feel as the pros for the player looking to take the next step.",
        price: "$89.99",
        size: "11\"",
        pocket: "Open",
        color: "Black",
        position: "Infield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gpsl1100-prspct-select-11in/312568",
        uuid: "9d71288f-f4ea-4b11-87db-af99b840784a"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "PROSPECT SERIES YOUTH BASEBALL FIRST BASE MITT 12.5\"",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prospect-series-youth-baseball-first-base-mitt-12.5.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-prospect-series-youth-baseball-first-base-mitt-12.5-1.jpeg",
        description: "Mizuno Prospect Series uses full grain pigskin leather, providing great durability, enhanced softness, and Mizuno’s innovative easy close technologies, making catching easy. All to help your Prospect learn to love the game.",
        price: "$110.00",
        size: "12.5\"",
        pocket: "Open",
        color: "Black",
        position: "First base",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.mizunousa.com/ca/product/baseball-gxf102-prospect-youth-fbm/312110?isB=true",
        uuid: "0f97a7a3-8530-44c0-a38e-0390717220fb"
    },
    {
        brand: "Mizuno",
        brand_id: 1,
        category: "gloves",
        name: "Classic Pro Soft 12.75\" Baseball Glove",
        image1: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-class-pro-outfield-baseball-12.75-glove.jpeg",
        image2: "https://equipmeserver.herokuapp.com/images/gloves/mizuno/mizuno-class-pro-outfield-baseball-12.75-glove-1.jpeg",
        description: "This Mizuno Classic Pro Soft Series (GCP82S3) baseball glove has a 12.75-inch opening, an H-web and a conventional open back. Made specifically for outfield players, this glove has a deep pocket that makes it easy to capture that last out on running catches deep to the wall. The H-web makes it easier to see the ball right before a transfer. Designed with professional patterns, this line of gloves is created for some of the best players in the game, and it bears the Mizuno patch of quality. Order yours today and enjoy free shipping. Don’t forget, with our 24/7 customer service, we’ll be here for you from click to catch!",
        price: "$275.00",
        size: "12.75\"",
        pocket: "Open",
        color: "Brown, Blonde",
        position: "Outfield",
        sport: "Baseball",
        left: "yes",
        right: "yes",
        whereToBuy: "https://www.cheapbats.com/shop/closeout-mizuno-classic-pro-soft-baseball-glove-1275-gcp82s3-312689-p-10080.html",
        uuid: "a518de29-56f3-4020-b4c9-9ee5c58faa4c"
    }
];